DROP DATABASE IF EXISTS glowstone_test;
CREATE DATABASE glowstone_test;
USE glowstone_test;

--
CREATE TABLE THUMBNAIL
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  thumbnail LONGBLOB NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE NOTE_GROUP
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name TINYTEXT DEFAULT "note group",
  thumbnail_id INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (thumbnail_id) REFERENCES THUMBNAIL(id)
);

CREATE TABLE NOTE
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  content LONGTEXT NOT NULL,
  name TINYTEXT DEFAULT "note",
  group_id INT UNSIGNED NOT NULL,
  thumbnail_id INT UNSIGNED,
  PRIMARY KEY (id),
  FOREIGN KEY (group_id) REFERENCES NOTE_GROUP(id),
  FOREIGN KEY (thumbnail_id) REFERENCES THUMBNAIL(id)
);

CREATE TABLE NOTE_CATEGORY
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name TINYTEXT NOT NULL,
  color TINYTEXT DEFAULT "FF0000",
  PRIMARY KEY (id)
);

CREATE TABLE NOTE_GROUP_CATEGORY
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name TINYTEXT NOT NULL,
  color TINYTEXT DEFAULT "FF0000",
  PRIMARY KEY (id)
);

CREATE TABLE NOTE_HAS
(
  note_id INT UNSIGNED NOT NULL,
  note_category_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (note_id, note_category_id),
  FOREIGN KEY (note_id) REFERENCES NOTE(id),
  FOREIGN KEY (note_category_id) REFERENCES NOTE_CATEGORY(id)
);

CREATE TABLE GROUP_HAS
(
  group_id INT UNSIGNED NOT NULL,
  group_category_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (group_id, group_category_id),
  FOREIGN KEY (group_id) REFERENCES NOTE_GROUP(id),
  FOREIGN KEY (group_category_id) REFERENCES NOTE_GROUP_CATEGORY(id)
);