# Use root/example as user/password credentials

services:

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8000:8080
